name: Docker Compose CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/ssh_private_key
          chmod 600 /tmp/ssh_private_key
          ssh -o "StrictHostKeyChecking=no" -i /tmp/ssh_private_key ${SSH_USERNAME}@${SSH_HOSTNAME} "
            sudo docker-compose pull;
            sudo docker-compose stop;
            sudo docker-compose rm -f;
            sudo docker-compose up -d;
            sudo docker system prune -f;
          "
